### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by aoddssa** [gingerchicken/shulker-dupe-rewritten#2]
Can you make a tutorial / more detailed readme on how to use the mod / installing? Please and thank you.

**Comment by gingerchicken** [comment]
I mean I can do but please note that this is patched on 1.19+

**Comment by gingerchicken** [comment]
Not going to lie, I didn't really ever plan on working on this project again as I have been feeling a little burnt out of Minecraft as of recently so it maybe a while before I resolve this issue.

**Comment by aoddssa** [comment]
> I mean I can do but please note that this is patched on 1.19+

I only use 1.18 so its fine

**Comment by aoddssa** [comment]
> Not going to lie, I didn't really ever plan on working on this project again as I have been feeling a little burnt out of Minecraft as of recently so it maybe a while before I resolve this issue.

Idc abt 1.19 I just would like to know how to install / use it on 1.18.2

**Comment by aoddssa** [comment]
Also is it for Jave or bedrock?

**Comment by gingerchicken** [comment]
It is for Java Edition and runs on fabric

**Comment by gingerchicken** [comment]
I will add documentation plus a release build for as soon as possible.
